#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/wordpress
- name: Incluir variables segun sistema operativo
  include_vars: "{{ ansible_os_family }}.yml"

- name: Instalar Apache
  ansible.builtin.apt:
    name: apache2
    update_cache: yes
    state: present

- name: Copiar archivo de configuracion
  ansible.builtin.template:
    src: apache-wp.conf.j2
    dest: /etc/apache2/sites-available/001-wp.conf
  when: ansible_os_family == "Debian"
  notify: Reiniciar Apache

- name: Copiar archivo de configuracion
  ansible.builtin.template:
    src: apache-wp.conf.j2
    dest: /etc/httpd/conf.d/001-wp.conf
  when: ansible_os_family == "RedHat"
  notify: Reiniciar Apache

- name: Instalar PHP
  ansible.builtin.package:
    name: "{{ php_packages }}"
    state: present


#- name: Habilitar php-fpm
#  ansible.builtin.shell:
#    "a2enconf php{{ php_version }}-fpm"
#  notify: Reiniciar Apache

- name: Deshabilitar sitio default Apache
  ansible.builtin.shell:
    a2dissite 000-default.conf
  notify: Reiniciar Apache

- name: Habilitar configuracion sitio PHP
  ansible.builtin.shell:
    a2ensite 001-wp.conf
  notify: Reiniciar Apache
   
- name: Crear directorio de Wordpress
  ansible.builtin.file:
    path: "{{ wordpress_dir }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: '0755'

- name: Descargar Wordpress
  ansible.builtin.unarchive:
    src: https://wordpress.org/wordpress-6.1.tar.gz
    dest: "{{ wordpress_dir }}"
    remote_src: yes
    creates: "{{ wordpress_dir }}/wordpress"

- name: Otorgar permisos al grupo
  ansible.builtin.file:
    path: "{{ wordpress_dir }}/wordpress"
    state: directory
    owner: "www-data"
    group: "www-data"
    recurse: yes

- name: Otorgar permisos para directorios a 755
  ansible.builtin.find:
    paths: "{{ wordpress_dir }}/wordpress"
    file_type: directory
  register: wordpress_dirs

- name: Aplicar permisos 755 a directorios
  ansible.builtin.file:
    path: "{{ item.path }}" #Item.path es el path a uno de los archivos dentro de wordpress_dirs.files
    mode: '0755'
  loop: "{{ wordpress_dirs.files }}"

- name: Otorgar permisos a archivos 644
  ansible.builtin.find:
    paths: "{{ wordpress_dir }}/wordpress"
    file_type: file
  register: wordpress_files

- name: Aplicar permisos 644 a archivos
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: '0644'
  loop: "{{ wordpress_files.files }}"

#- name: Setear permisos para directorios
#  shell: "/usr/bin/find {{ wordpress_dir }}/wordpress/ -type d -exec chmod 750 {} \\;"


#- name: Setear permisos para archivos
#  shell: "/usr/bin/find {{ wordpress_dir }}/wordpress/ -type f -exec chmod 640 {} \\;"

- name: Set up wp-config
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: "{{ wordpress_dir }}/wordpress/wp-config.php"
